# Site settings
title: Binary.com Developers
url: "https://developers.binary.me"
twitter_username: binarydotcom
github_username:  binary-com

# Build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/
